name: pytest steps
description: 'Common deployment steps'

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        # sudo apt-get update && sudo apt-get install -y --no-install-recommends \
        # wget \     
        # git \
        # ca-certificates \
        # curl \
        # vim \
        # dos2unix 

        echo "当前执行用户是====================="
        whoami
        
        echo "开始执行installconda.sh 文件====================="
        wget -q $PY_URL -O miniconda.sh
        bash miniconda.sh -b -p /opt/miniconda3
        rm miniconda.sh
        
        echo "启动conda base 环境====================="
        source /opt/miniconda3/etc/profile.d/conda.sh
        conda activate base
        PATH=/opt/miniconda3/bin:${PATH}
        echo "/opt/miniconda3/bin" >> $GITHUB_PATH
        
        
        echo "python版本是："
        python --version
        echo "pip执行路径是："
        which pip
        echo "PATH路径是："
        echo $PATH
         
        
        sed -i "s|MinicondaURL|$PY_URL|g" $GITHUB_WORKSPACE/Dockerfile
        
        if [[ "$PY_URL" == "https://repo.anaconda.com/miniconda/Miniconda3-4.5.1-Linux-x86_64.sh" ]]; then
            echo "检测到特定 Miniconda 版本，替换 conda 初始化命令..."
            sed -i 's|^RUN conda init bash && conda config --add channels conda-forge && conda config --remove channels defaults$|RUN conda config --add channels conda-forge|' $GITHUB_WORKSPACE/Dockerfile
        fi
      
        echo "开始写入setup_repo.sh 文件====================="
        cat > setup_repo.sh << EOF
        #!/bin/bash
        mkdir -p /testbed
        git clone $REPO_URL /testbed/$REPO_DIR
        cd /testbed/$REPO_DIR
        git checkout "$base_commit"
        cd ..
        EOF
        
        echo "开始执行setup_repo.sh 脚本====================="
        sudo bash setup_repo.sh

    
        echo "开始执行setup_env 脚本====================="
        bash setup_env.sh
       
        echo "pytest版本是："
        pytest --version 
        echo "pytest路径是："
        which pytest
        
        echo "开始写入pytest.sh 脚本====================="
        cat > pytest.sh << EOF
        #!/bin/bash
        cd /testbed/$REPO_DIR
        pytest $TEST_FILE
        git apply $GITHUB_WORKSPACE/$INSTANCE_DIR/test.patch 
        pytest $TEST_FILE || true
        git apply $GITHUB_WORKSPACE/$INSTANCE_DIR/code.patch 
        pytest $TEST_FILE
        EOF
        
        echo "开始执行pytest.sh 脚本====================="
        if [[ "$RUN_PYTEST" == 'true' ]]; then
            bash pytest.sh
        fi
    - name: run verification
      shell: bash
      continue-on-error: true
      run: |
        echo "python版本是："
        python --version
        
        # 使用 sed 替换变量值
        sed -i "s|REPO_PATH = ''|REPO_PATH = '$REPO_DIR'|g" run_verification.py
        sed -i "s|BASE_COMMIT = ''|BASE_COMMIT = '$base_commit'|g" run_verification.py
        sed -i "s|INSTANCE_ID = ''|INSTANCE_ID = '$INSTANCE_DIR'|g" run_verification.py
    
        # 验证替换结果
        echo "=== 替换后的变量值 ==="
        grep -E "^(REPO_PATH|BASE_COMMIT|INSTANCE_ID) =" run_verification.py
        
        
        echo "开始写入run_verification.sh 脚本====================="
        cat > run_verification.sh << EOF
        #!/bin/bash
        source /opt/miniconda3/etc/profile.d/conda.sh
        conda activate base
        cd /testbed
        cp $GITHUB_WORKSPACE/run_verification.py .
        cp $GITHUB_WORKSPACE/$INSTANCE_DIR/test.patch .
        cp $GITHUB_WORKSPACE/$INSTANCE_DIR/code.patch .
        python run_verification.py 
        EOF
        
        echo "开始执行run_verification.sh 脚本====================="
        bash run_verification.sh
        
        cp /testbed/results.json $GITHUB_WORKSPACE/
        cp /testbed/test.patch $GITHUB_WORKSPACE/
        cp /testbed/code.patch $GITHUB_WORKSPACE/
        
    - name: mergejson
      shell: bash
      run: |
      
        sed -i "s|INSTANCE_DIR|$INSTANCE_DIR|g" mergejson.py
        
        echo "开始执行mergejson.py 合并程序====================="
        cp $INSTANCE_DIR/$INSTANCE_DIR.json $GITHUB_WORKSPACE/
        python mergejson.py
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.INSTANCE_DIR }}
        path: |
            Dockerfile
            setup_env.sh
            setup_repo.sh
            run_verification.py
            ${{ env.INSTANCE_DIR }}.json
            test.patch
            code.patch
