name: pytest verification

runs:
  using: "composite"
  steps:
      - name: Download artifact from verification
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.INSTANCE_DIR }}  # 必须和 upload 时的 name 一致
          path: ./downloaded-reports  # 下载到这个目录
          
      - name: get setup_env
        shell: bash
        run: |
            echo "查看文件是否存在======================================"
            ls downloaded-reports
            python --version
            pip --version 
            docker --version
            pip install docker
            INSTANCE_DIR_LOWER=$(echo "$INSTANCE_DIR" | tr '[:upper:]' '[:lower:]')
            echo "构建镜像======================================"
            sed -i "/^IMAGE_NAME_TEMPLATE/s|INSTANCE_DIR|$INSTANCE_DIR_LOWER|g" dockerbuild.py
            python dockerbuild.py
            echo "验证镜像======================================"
            sed -i "/^IMAGE_NAME_TEMPLATE/s|INSTANCE_DIR|$INSTANCE_DIR_LOWER|g" verification.py
            python verification.py
            
      - name: mergejson
        shell: bash
        run: |
            sed -i "s|INSTANCE_DIR|$INSTANCE_DIR|g" mergejson.py
            echo "开始执行mergejson.py 合并程序====================="
            cp downloaded-reports/$INSTANCE_DIR.json $GITHUB_WORKSPACE/
            python mergejson.py