name: pytest verification

runs:
  using: "composite"
  steps:

      - name: get setup_env
        shell: bash
        run: |
            echo "解压文件======================================"
            unzip zipfile/${INSTANCE_DIR}.zip -d downloaded-reports
            echo "查看文件是否存在======================================"
            ls downloaded-reports
            python --version
            pip --version 
            docker --version
            pip install docker
            INSTANCE_DIR_LOWER=$(echo "$INSTANCE_DIR" | tr '[:upper:]' '[:lower:]')
            echo "构建镜像======================================"
            sed -i "/^IMAGE_NAME_TEMPLATE/s|INSTANCE_DIR|$INSTANCE_DIR_LOWER|g" dockerbuild.py
            python dockerbuild.py
            echo "验证镜像======================================"
            sed -i "/^IMAGE_NAME_TEMPLATE/s|INSTANCE_DIR|$INSTANCE_DIR_LOWER|g" verification.py
            python verification.py
            