name: pytest verification

on:
  push:
    branches: [zhijian]

env:
  INSTANCE_DIR: spack__spack-14390
 
  
jobs:  
            
  call-docker-verification:
    name: docker-verification
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Execute docker-verification steps
      uses: ./.github/actions/docker-verification